# Generated by Django 5.2.11 on 2026-03-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_medecin_heures_par_defaut'),
        ('employees', '0006_collaborateur_plant_section_collaborateur_segment'),
        ('medical_work', '0015_remove_demandebilan_renseignements_cliniques_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeEmbauche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_visite', models.DateField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('EN_TRAITEMENT', 'En traitement'), ('CLOTUREE', 'Cloturee')], default='BROUILLON', max_length=20)),
                ('fichier_excel', models.FileField(blank=True, null=True, upload_to='embauche/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listes_embauche_creees', to='account.profile')),
            ],
            options={
                'verbose_name': 'Liste embauche',
                'verbose_name_plural': 'Listes embauche',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CandidatEmbauche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligne_source', models.PositiveIntegerField(default=0)),
                ('matricule', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('cin', models.CharField(blank=True, max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('poste', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('presence', models.CharField(choices=[('NON_RENSEIGNEE', 'Non renseignee'), ('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='NON_RENSEIGNEE', max_length=20)),
                ('etat_embauche', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APTE', 'Apte'), ('INAPTE', 'Inapte')], default='EN_ATTENTE', max_length=20)),
                ('observations_medecin', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_embauche', to='employees.collaborateur')),
                ('fiche_aptitude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats_embauche', to='medical_work.ficheaptitude')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='embauche.listeembauche')),
            ],
            options={
                'verbose_name': 'Candidat embauche',
                'verbose_name_plural': 'Candidats embauche',
                'ordering': ['liste_id', 'id'],
            },
        ),
    ]
