# Generated by Django 5.2.11 on 2026-03-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embauche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatembauche',
            name='centre_cout',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidatembauche',
            name='date_recrutement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatembauche',
            name='formation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidatembauche',
            name='genre',
            field=models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10),
        ),
        migrations.AddField(
            model_name='candidatembauche',
            name='gouvernorat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidatembauche',
            name='niveau',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidatembauche',
            name='num_demande',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidatembauche',
            name='projet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidatembauche',
            name='ps',
            field=models.CharField(blank=True, max_length=100, verbose_name='PS'),
        ),
        migrations.AddField(
            model_name='candidatembauche',
            name='source_information',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='candidatembauche',
            name='poste',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='candidatembauche',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
