# Generated by Django 5.2.11 on 2026-03-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embauche', '0002_add_missing_fields_to_candidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatembauche',
            name='statut_integration',
            field=models.CharField(choices=[('EN_ATTENTE_VISITE', 'En attente visite'), ('EN_FORMATION', 'En formation'), ('INTEGRE', 'Integre'), ('NON_RETENU', 'Non retenu')], default='EN_ATTENTE_VISITE', max_length=30),
        ),
    ]
