# Generated by Django 5.2.11 on 2026-03-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embauche', '0003_add_statut_integration'),
        ('planning', '0003_alter_listepassage_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeembauche',
            name='liste_passage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liste_embauche_o2o', to='planning.listepassage'),
        ),
    ]
