# Generated by Django 5.2.11 on 2026-03-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embauche', '0004_add_visite_embauche_and_fk_liste_embauche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeembauche',
            name='liste_passage',
        ),
    ]
