# Generated by Django 5.2.11 on 2026-03-22 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_medecin_heures_par_defaut'),
        ('embauche', '0005_revert_fk_liste_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeembauche',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listes_embauche_assignees', to='account.medecin'),
        ),
    ]
