# Generated by Django 5.2.11 on 2026-03-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embauche', '0006_add_medecin_to_liste_embauche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeembauche',
            name='date_visite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
