from .consultation_models import *
from .ordonnance_models import *
from .ligne_ordonnance_models import *
from .certificat_models import *
from .certificat_aptitude_models import *
from .certificat_exemption_models import *
from .certificat_bonne_sante_models import *
from .certificat_permis_models import *
from .certificat_prenuptial_models import *
from .posologie_models import PosologieStandard