# Generated by Django 5.2.11 on 2026-02-22 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListePassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('session', models.CharField(choices=[('MATIN', 'Matin'), ('APRES_MIDI', 'Après-midi')], max_length=20)),
                ('type_liste', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('CONTRE_VISITE', 'Contre visite')], max_length=30)),
                ('statut', models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('ACTIVE', 'Active'), ('TERMINEE', 'Terminée')], default='EN_PREPARATION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.medecin')),
            ],
            options={
                'verbose_name': 'Liste de passage',
                'verbose_name_plural': 'Listes de passage',
                'ordering': ['-date', 'session'],
                'unique_together': {('date', 'session', 'medecin', 'type_liste')},
            },
        ),
        migrations.CreateModel(
            name='ItemPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EFFECTUEE', 'Effectuée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.listepassage')),
            ],
            options={
                'verbose_name': 'Item de passage',
                'verbose_name_plural': 'Items de passage',
                'ordering': ['ordre'],
            },
        ),
    ]
