# Generated by Django 5.2.11 on 2026-02-22 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempassage',
            name='collaborateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.collaborateur'),
        ),
    ]
