# Generated by Django 5.2.11 on 2026-02-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_itempassage_collaborateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listepassage',
            name='session',
            field=models.CharField(choices=[('MATIN', 'Matin'), ('MIDI', 'Midi'), ('APRES_MIDI', 'Après-midi')], max_length=20),
        ),
    ]
