# Generated by Django 5.2.11 on 2026-03-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embauche', '0004_add_visite_embauche_and_fk_liste_embauche'),
        ('planning', '0003_alter_listepassage_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='listepassage',
            name='liste_embauche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listes_passage', to='embauche.listeembauche'),
        ),
        migrations.AlterField(
            model_name='listepassage',
            name='type_liste',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('CONTRE_VISITE', 'Contre visite'), ('VISITE_EMBAUCHE', 'Visite embauche')], max_length=30),
        ),
    ]
