# Generated by Django 5.2.11 on 2026-03-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_add_visite_embauche_and_fk_liste_embauche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listepassage',
            name='liste_embauche',
        ),
        migrations.AlterField(
            model_name='listepassage',
            name='type_liste',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('CONTRE_VISITE', 'Contre visite')], max_length=30),
        ),
    ]
