# Generated by Django 5.2.11 on 2026-04-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_revert_liste_passage_embauche'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempassage',
            name='sms_envoye',
            field=models.BooleanField(default=False),
        ),
    ]
