# Generated by Django 5.2.11 on 2026-02-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('num_portable', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
            ],
        ),
    ]
