# Generated by Django 5.2.11 on 2026-02-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborateur',
            old_name='num_portable',
            new_name='telephone',
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='collaborateurs/photos/'),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
    ]
