# Generated by Django 5.2.11 on 2026-02-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_num_portable_collaborateur_telephone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateur',
            name='photo',
        ),
    ]
