# Generated by Django 5.2.11 on 2026-03-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_collaborateur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='cin',
            field=models.CharField(blank=True, max_length=20, verbose_name='CIN'),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='adresse',
            field=models.TextField(blank=True, default='', verbose_name='Adresse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
    ]
