# Generated by Django 5.2.11 on 2026-03-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_collaborateur_cin_collaborateur_lieu_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='numero_cnss',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro CNSS'),
        ),
    ]
