# Generated by Django 5.2.11 on 2026-03-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_collaborateur_numero_cnss'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='plant_section',
            field=models.CharField(blank=True, max_length=150, verbose_name='Plant_Section'),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='segment',
            field=models.CharField(blank=True, max_length=150, verbose_name='Segment'),
        ),
    ]
