# Generated by Django 5.2.11 on 2026-03-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_collaborateur_plant_section_collaborateur_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceIM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('CIN', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('mail', models.CharField(blank=True, max_length=150, null=True)),
                ('adress', models.TextField(blank=True, null=True)),
                ('adr_ville', models.CharField(blank=True, max_length=100, null=True)),
                ('adr_gouv', models.CharField(blank=True, max_length=100, null=True)),
                ('gouvernorat_act', models.CharField(blank=True, max_length=100, null=True)),
                ('Code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('fonction', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('ccenter', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau', models.CharField(blank=True, max_length=50, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('specialite', models.CharField(blank=True, max_length=150, null=True)),
                ('affectation', models.CharField(blank=True, max_length=150, null=True)),
                ('date_embauche', models.CharField(blank=True, max_length=20, null=True)),
                ('date_entree', models.CharField(blank=True, max_length=20, null=True)),
                ('CNSS', models.CharField(blank=True, max_length=50, null=True)),
                ('status_actif', models.CharField(blank=True, max_length=50, null=True)),
                ('Situation_familiale', models.CharField(blank=True, max_length=30, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'resources',
                'managed': False,
            },
        ),
    ]
