# Generated by Django 5.2.11 on 2026-03-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_resourceim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateur',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='department',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='plant_section',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='telephone',
        ),
        migrations.AlterModelTable(
            name='resourceim',
            table='resource',
        ),
    ]
