# Generated by Django 5.2.11 on 2026-03-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_remove_collaborateur_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateur',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='lieu_naissance',
        ),
    ]
