# Generated by Django 5.2.11 on 2026-03-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipementmedicalendommage',
            options={'ordering': ['-date_constat'], 'verbose_name': 'Équipement médical endommagé', 'verbose_name_plural': 'Équipements médicaux endommagés'},
        ),
        migrations.AlterModelOptions(
            name='parametrehseemensuel',
            options={'ordering': ['-annee', '-mois'], 'verbose_name': 'Paramètre HSEE mensuel', 'verbose_name_plural': 'Paramètres HSEE mensuels'},
        ),
    ]
