# Generated by Django 5.2.11 on 2026-03-30 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_infirmier', '0015_alter_documentmedicalscanne_matricule_ref'),
        ('hsee', '0002_alter_equipementmedicalendommage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHSSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_hsse', to='act_infirmier.accidenttravail', verbose_name='Accident de travail')),
                ('enquete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_hsse', to='act_infirmier.enqueteaccident', verbose_name='Enquête accident')),
            ],
            options={
                'verbose_name': 'Notification HSSE',
                'verbose_name_plural': 'Notifications HSSE',
                'ordering': ['-date_creation'],
            },
        ),
    ]
