# Generated by Django 5.2.11 on 2026-02-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text="L'utilisateur doit changer son mot de passe à la première connexion"),
        ),
    ]
