# Generated by Django 5.2.11 on 2026-03-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_create_groups_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='heures_par_defaut',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
