# Generated by Django 5.2.11 on 2026-04-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_medecin_heures_par_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='adresse_cabinet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medecin',
            name='lieu_exercice_medecin',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
