# Generated by Django 5.2.11 on 2026-04-08 12:06

from django.db import migrations, models


def copy_adresse_cabinet_to_adresse_numero_rue(apps, schema_editor):
    Medecin = apps.get_model('account', 'Medecin')
    for medecin in Medecin.objects.all().only('id', 'adresse_cabinet', 'adresse_numero_rue'):
        if medecin.adresse_cabinet and not medecin.adresse_numero_rue:
            medecin.adresse_numero_rue = medecin.adresse_cabinet
            medecin.save(update_fields=['adresse_numero_rue'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_medecin_adresse_cabinet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='adresse_numero_rue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medecin',
            name='gouvernorat_cabinet',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='medecin',
            name='ville_cabinet',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(copy_adresse_cabinet_to_adresse_numero_rue, noop_reverse),
        migrations.RemoveField(
            model_name='medecin',
            name='adresse_cabinet',
        ),
    ]
