# Generated by Django 5.2.11 on 2026-04-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_update_site_template_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsee',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hsees', to='account.site'),
        ),
        migrations.AddField(
            model_name='infirmier',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infirmiers', to='account.site'),
        ),
        migrations.AddField(
            model_name='rh',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rhs', to='account.site'),
        ),
    ]
