# Generated by Django 5.2.11 on 2026-04-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_hsee_site_infirmier_site_rh_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='nom_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medecin',
            name='prenom_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
