# Generated by Django 5.2.11 on 2026-04-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_medecin_nom_ar_medecin_prenom_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='nature_activite',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nature d'activité"),
        ),
        migrations.AddField(
            model_name='site',
            name='numero_cnss',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro CNSS'),
        ),
        migrations.AddField(
            model_name='site',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=255, verbose_name='Raison sociale'),
        ),
    ]
