# Generated by Django 5.2.11 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_site_nature_activite_site_numero_cnss_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="adresse_entreprise",
            field=models.TextField(blank=True, default="", verbose_name="Adresse entreprise"),
        ),
        migrations.AddField(
            model_name="site",
            name="numero_cnss_entreprise",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Numéro CNSS Entreprise",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="qualifications",
            field=models.TextField(blank=True, default="", verbose_name="Qualifications"),
        ),
    ]

