# Generated by Cursor on 2026-05-06

from django.db import migrations, models


def forwards_rename_mater_to_mateur(apps, schema_editor):
    Site = apps.get_model("account", "Site")
    Site.objects.filter(template_key="MATER").update(template_key="MATEUR")


def reverse_rename_mateur_to_mater(apps, schema_editor):
    Site = apps.get_model("account", "Site")
    Site.objects.filter(template_key="MATEUR").update(template_key="MATER")


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0014_site_entreprise_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="template_key",
            field=models.CharField(
                choices=[("MONASTIR", "Monastir"), ("SOUSSE", "Sousse"), ("MATEUR", "Mateur")],
                default="MONASTIR",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            forwards_rename_mater_to_mateur,
            reverse_rename_mateur_to_mater,
        ),
    ]

