# Generated by Django 5.2.11 on 2026-02-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheAptitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField(verbose_name='Date de visite')),
                ('type_visite', models.CharField(choices=[('EMBAUCHE', "Visite d'Embauche"), ('PERIODIQUE', 'Visite Périodique'), ('REPRISE', 'Visite de Reprise'), ('SPONTANEE', 'Visite Spontanée')], max_length=20, verbose_name='Type de visite')),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('taille', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taille (cm)')),
                ('tension_arterielle', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tension artérielle')),
                ('vision_droite', models.CharField(blank=True, max_length=10, null=True, verbose_name='Vision œil droit')),
                ('vision_gauche', models.CharField(blank=True, max_length=10, null=True, verbose_name='Vision œil gauche')),
                ('observations_cliniques', models.TextField(blank=True, verbose_name='Observations cliniques')),
                ('aptitude', models.CharField(choices=[('APTE', 'Apte'), ('APTE_RESTRICTIONS', 'Apte avec restrictions'), ('INAPTE_TEMPORAIRE', 'Inapte temporaire'), ('INAPTE_DEFINITIF', 'Inapte définitif')], max_length=30, verbose_name='Aptitude')),
                ('restrictions', models.TextField(blank=True, verbose_name='Restrictions')),
                ('date_prochaine_visite', models.DateField(verbose_name='Date prochaine visite')),
                ('validite_mois', models.IntegerField(default=12, verbose_name='Validité (mois)')),
                ('envoyee_rh', models.BooleanField(default=False, verbose_name='Envoyée au RH')),
                ('date_envoi_rh', models.DateTimeField(blank=True, null=True, verbose_name='Date envoi RH')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_aptitude', to='employees.collaborateur', verbose_name='Collaborateur')),
                ('medecin_travail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_creees', to='account.medecin', verbose_name='Médecin du Travail')),
            ],
            options={
                'verbose_name': "Fiche d'Aptitude",
                'verbose_name_plural': "Fiches d'Aptitude",
                'db_table': 'fiches_aptitude',
                'ordering': ['-date_visite'],
            },
        ),
        migrations.CreateModel(
            name='DemandeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(max_length=50, unique=True, verbose_name='N° Demande')),
                ('date_demande', models.DateField(verbose_name='Date de demande')),
                ('type_examen', models.CharField(choices=[('RADIO_THORAX', 'Radiographie thorax'), ('RADIO_COLONNE', 'Radiographie colonne'), ('ECG', 'Électrocardiogramme'), ('SPIROMETRIE', 'Spirométrie'), ('AUDIOMETRIE', 'Audiométrie'), ('TEST_VISION', 'Test vision'), ('AUTRE', 'Autre')], max_length=30, verbose_name="Type d'examen")),
                ('indication', models.TextField(verbose_name='Indication médicale')),
                ('centre_examen', models.CharField(blank=True, max_length=200, verbose_name="Centre d'examen")),
                ('urgence', models.BooleanField(default=False, verbose_name='Urgent')),
                ('resultat_recu', models.BooleanField(default=False, verbose_name='Résultat reçu')),
                ('date_resultat', models.DateField(blank=True, null=True, verbose_name='Date résultat')),
                ('interpretation', models.TextField(blank=True, verbose_name='Interprétation')),
                ('fiche_aptitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_examen', to='medical_work.ficheaptitude', verbose_name="Fiche d'Aptitude")),
            ],
            options={
                'verbose_name': "Demande d'Examen",
                'verbose_name_plural': "Demandes d'Examen",
                'db_table': 'demandes_examen',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='DemandeBilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(max_length=50, unique=True, verbose_name='N° Demande')),
                ('date_demande', models.DateField(verbose_name='Date de demande')),
                ('type_bilan', models.CharField(choices=[('SANGUIN', 'Bilan sanguin complet'), ('URINAIRE', 'Bilan urinaire'), ('HEPATIQUE', 'Bilan hépatique'), ('RENAL', 'Bilan rénal'), ('LIPIDIQUE', 'Bilan lipidique'), ('GLYCEMIE', 'Glycémie')], max_length=30, verbose_name='Type de bilan')),
                ('examens_demandes', models.TextField(verbose_name='Examens demandés (détails)')),
                ('indication', models.TextField(verbose_name='Indication médicale')),
                ('laboratoire', models.CharField(blank=True, max_length=200, verbose_name='Laboratoire')),
                ('urgence', models.BooleanField(default=False, verbose_name='Urgent')),
                ('resultat_recu', models.BooleanField(default=False, verbose_name='Résultat reçu')),
                ('date_resultat', models.DateField(blank=True, null=True, verbose_name='Date résultat')),
                ('fiche_aptitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_bilan', to='medical_work.ficheaptitude', verbose_name="Fiche d'Aptitude")),
            ],
            options={
                'verbose_name': 'Demande de Bilan',
                'verbose_name_plural': 'Demandes de Bilan',
                'db_table': 'demandes_bilan',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='CertificatAptitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificat', models.CharField(max_length=50, unique=True, verbose_name='N° Certificat')),
                ('date_emission', models.DateField(verbose_name="Date d'émission")),
                ('resultat_aptitude', models.CharField(max_length=30, verbose_name='Résultat')),
                ('restrictions', models.TextField(blank=True, verbose_name='Restrictions détaillées')),
                ('amenagement_poste', models.TextField(blank=True, verbose_name='Aménagement de poste nécessaire')),
                ('date_validite_fin', models.DateField(verbose_name="Valide jusqu'au")),
                ('fiche_aptitude', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='medical_work.ficheaptitude', verbose_name="Fiche d'Aptitude")),
            ],
            options={
                'verbose_name': "Certificat d'Aptitude",
                'verbose_name_plural': "Certificats d'Aptitude",
                'db_table': 'certificats_aptitude',
                'ordering': ['-date_emission'],
            },
        ),
    ]
