# Generated by Django 5.2.11 on 2026-03-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificataptitude',
            name='amenagement_poste',
        ),
        migrations.RemoveField(
            model_name='certificataptitude',
            name='date_validite_fin',
        ),
        migrations.RemoveField(
            model_name='certificataptitude',
            name='numero_certificat',
        ),
        migrations.RemoveField(
            model_name='certificataptitude',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='certificataptitude',
            name='resultat_aptitude',
        ),
        migrations.RemoveField(
            model_name='demandebilan',
            name='examens_demandes',
        ),
        migrations.RemoveField(
            model_name='demandebilan',
            name='laboratoire',
        ),
        migrations.RemoveField(
            model_name='demandebilan',
            name='type_bilan',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='centre_examen',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='interpretation',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='type_examen',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='observations_cliniques',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='tension_arterielle',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='validite_mois',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='vision_droite',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='vision_gauche',
        ),
        migrations.AddField(
            model_name='certificataptitude',
            name='description',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='acide_urique',
            field=models.BooleanField(default=False, verbose_name='Acide urique'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='cholestorol',
            field=models.BooleanField(default=False, verbose_name='Cholestérol'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='cin',
            field=models.CharField(blank=True, max_length=50, verbose_name='CIN'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='copro_parasitologique',
            field=models.BooleanField(default=False, verbose_name='Copro parasitologique'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='creatinine',
            field=models.BooleanField(default=False, verbose_name='Créatinine'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='entreprise',
            field=models.CharField(blank=True, max_length=255, verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='glycemie',
            field=models.BooleanField(default=False, verbose_name='Glycémie'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='gsm',
            field=models.CharField(blank=True, max_length=20, verbose_name='GSM'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='nfs',
            field=models.BooleanField(default=False, verbose_name='NFS'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='nom_prenom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom et prénom'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='poste_de_travail',
            field=models.CharField(blank=True, max_length=150, verbose_name='Poste de travail'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='transaminases',
            field=models.BooleanField(default=False, verbose_name='Transaminases'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='triglycerides',
            field=models.BooleanField(default=False, verbose_name='Triglycérides'),
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='vs',
            field=models.BooleanField(default=False, verbose_name='VS'),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='audiogramme',
            field=models.BooleanField(default=False, verbose_name='Audiogramme'),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='ecg',
            field=models.BooleanField(default=False, verbose_name='ECG'),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='efr',
            field=models.BooleanField(default=False, verbose_name='EFR'),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='entreprise',
            field=models.CharField(blank=True, max_length=255, verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='nom_prenom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom et prénom'),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='poste_de_travail',
            field=models.CharField(blank=True, max_length=150, verbose_name='Poste de travail'),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='visiotest',
            field=models.BooleanField(default=False, verbose_name='Visiotest'),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='date_lieu_naissance',
            field=models.CharField(blank=True, max_length=255, verbose_name='Date et lieu de naissance'),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='date_recrutement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de recrutement'),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='medecin_certifie',
            field=models.CharField(blank=True, max_length=255, verbose_name='Médecin certifié'),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='nature_activite',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nature d'activité"),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='nom_prenom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom et prénom'),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='numero_cnss',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro CNSS'),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='poste_de_travail',
            field=models.CharField(blank=True, max_length=150, verbose_name='Poste de travail'),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='precision_aptitude',
            field=models.TextField(blank=True, verbose_name='Précision aptitude'),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='qualifications',
            field=models.TextField(blank=True, verbose_name='Qualifications'),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=255, verbose_name='Raison sociale'),
        ),
        migrations.AlterField(
            model_name='ficheaptitude',
            name='aptitude',
            field=models.CharField(choices=[('APTE_AU_POSTE', 'APTE_AU_POSTE'), ('APTE_AMENAGEMENT_POSTE', 'APTE_AMENAGEMENT_POSTE'), ('INAPTE_TEMPORAIRE', 'Inapte temporaire'), ('INAPTE_DEFINITIF_MEME_POSTE', 'INAPTE_DEFINITIF_MEME_POSTE'), ('INAPTE_DEFINITIF_ENTREPRISE', 'INAPTE_DEFINITIF_ENTREPRISE')], max_length=30, verbose_name='Aptitude'),
        ),
    ]
