# Generated by Django 5.2.11 on 2026-03-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0002_remove_certificataptitude_amenagement_poste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandebilan',
            name='date_resultat',
        ),
        migrations.RemoveField(
            model_name='demandebilan',
            name='resultat_recu',
        ),
        migrations.RemoveField(
            model_name='demandebilan',
            name='urgence',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='date_resultat',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='resultat_recu',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='urgence',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='date_envoi_rh',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='date_prochaine_visite',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='envoyee_rh',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='medecin_certifie',
        ),
        migrations.RenameField(
            model_name='demandebilan',
            old_name='indication',
            new_name='renseignements_cliniques',
        ),
        migrations.AlterField(
            model_name='demandebilan',
            name='renseignements_cliniques',
            field=models.TextField(verbose_name='Renseignements cliniques'),
        ),
        migrations.RenameField(
            model_name='demandeexamen',
            old_name='indication',
            new_name='renseignements_cliniques',
        ),
        migrations.AlterField(
            model_name='demandeexamen',
            name='renseignements_cliniques',
            field=models.TextField(blank=True, verbose_name='Renseignements cliniques'),
        ),
    ]
