# Generated by Django 5.2.11 on 2026-03-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0003_remove_demandebilan_date_resultat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheaptitude',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matricule'),
        ),
    ]
