# Generated by Django 5.2.11 on 2026-03-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0005_medecin_travail_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandebilan',
            name='age',
        ),
        migrations.RemoveField(
            model_name='demandebilan',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='demandebilan',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='demandebilan',
            name='nom_prenom',
        ),
        migrations.RemoveField(
            model_name='demandebilan',
            name='numero_demande',
        ),
        migrations.RemoveField(
            model_name='demandebilan',
            name='poste_de_travail',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='age',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='nom_prenom',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='numero_demande',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='poste_de_travail',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='date_lieu_naissance',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='nom_prenom',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='poste_de_travail',
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='numero_labo',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Laboratoire'),
        ),
    ]
