# Generated by Django 5.2.11 on 2026-03-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0006_remove_demandebilan_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandebilan',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
    ]
