# Generated by Django 5.2.11 on 2026-03-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0007_demandebilan_age_demandeexamen_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandebilan',
            old_name='cholestorol',
            new_name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='demandebilan',
            name='age',
        ),
        migrations.RemoveField(
            model_name='demandebilan',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='demandebilan',
            name='gsm',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='age',
        ),
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='date_recrutement',
        ),
        migrations.AddField(
            model_name='demandebilan',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='adresse_entreprise',
            field=models.TextField(blank=True, verbose_name="Adresse de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='demandebilan',
            name='renseignements_cliniques',
            field=models.TextField(blank=True, verbose_name='Renseignements cliniques'),
        ),
    ]
