# Generated by Django 5.2.11 on 2026-03-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0008_rename_cholestorol_demandebilan_cholesterol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandebilan',
            name='nom_entreprise',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='nom_entreprise',
        ),
        migrations.AlterField(
            model_name='demandebilan',
            name='renseignements_cliniques',
            field=models.TextField(verbose_name='Renseignements cliniques'),
        ),
        migrations.AlterField(
            model_name='ficheaptitude',
            name='adresse_entreprise',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse entreprise'),
        ),
    ]
