# Generated by Django 5.2.11 on 2026-03-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0009_remove_demandebilan_nom_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeexamen',
            name='numero_examen',
            field=models.CharField(blank=True, default='', editable=False, max_length=20, verbose_name='N° Examen'),
        ),
    ]
