# Generated by Django 5.2.11 on 2026-03-04

from django.db import migrations


def populate_numero_examen(apps, schema_editor):
    DemandeExamen = apps.get_model('medical_work', 'DemandeExamen')

    counters = {}
    examens = DemandeExamen.objects.order_by('date_demande', 'id')

    for examen in examens:
        if examen.numero_examen:
            continue

        year = examen.date_demande.year if examen.date_demande else 2026
        counters[year] = counters.get(year, 0) + 1
        examen.numero_examen = f"EX-{year}-{counters[year]:03d}"
        examen.save(update_fields=['numero_examen'])


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0010_demandeexamen_numero_examen'),
    ]

    operations = [
        migrations.RunPython(populate_numero_examen, migrations.RunPython.noop),
    ]
