# Generated by Django 5.2.11 on 2026-03-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0011_populate_demandeexamen_numero_examen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheaptitude',
            name='numero_cnss',
        ),
        migrations.AddField(
            model_name='ficheaptitude',
            name='numero_cnss_entreprise',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro CNSS Entreprise'),
        ),
    ]
