# Generated by Django 5.2.11 on 2026-03-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0012_remove_ficheaptitude_numero_cnss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandebilan',
            name='cin',
            field=models.CharField(blank=True, max_length=50, verbose_name='CIN'),
        ),
    ]
