# Generated by Django 5.2.11 on 2026-03-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0013_demandebilan_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandebilan',
            name='cin',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='CIN'),
        ),
    ]
