# Generated by Django 5.2.11 on 2026-03-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0014_alter_demandebilan_cin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandebilan',
            name='renseignements_cliniques',
        ),
        migrations.RemoveField(
            model_name='demandeexamen',
            name='renseignements_cliniques',
        ),
    ]
