# Generated by Django 5.2.11 on 2026-03-22 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_collaborateur_plant_section_collaborateur_segment'),
        ('medical_work', '0015_remove_demandebilan_renseignements_cliniques_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheaptitude',
            name='collaborateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_aptitude', to='employees.collaborateur', verbose_name='Collaborateur'),
        ),
    ]
