# Generated by Django 5.2.11 on 2026-03-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0017_nullable_fiche_for_embauche_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheaptitude',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matricule (snapshot embauche)'),
        ),
    ]
