# Generated by Django 5.2.11 on 2026-03-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0018_ficheaptitude_matricule'),
        ('medical_work', '0018_renseignements_cliniques_demandes'),
    ]

    operations = [
    ]
