# Generated by Django 5.2.11 on 2026-04-09 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_site_medecin_site'),
        ('medical_work', '0022_ficheaptitude_ligne_visite_periodique'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheaptitude',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_aptitude', to='account.site', verbose_name='Site'),
        ),
    ]
