# Generated by Django 5.2.11 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_work", "0028_alter_ficheaptitude_aptitude_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="ficheaptitude",
            name="date_prochaine_visite",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date prochaine visite",
            ),
        ),
        migrations.AddField(
            model_name="ficheaptitude",
            name="validite_mois",
            field=models.IntegerField(default=12, verbose_name="Validité (mois)"),
        ),
        migrations.AddField(
            model_name="ficheaptitude",
            name="envoyee_rh",
            field=models.BooleanField(default=False, verbose_name="Envoyée au RH"),
        ),
        migrations.AddField(
            model_name="ficheaptitude",
            name="date_envoi_rh",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Date envoi RH",
            ),
        ),
    ]

