# Generated by Django 5.2.11 on 2026-05-03 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0030_ficheaptitude_observations_complementaires'),
        ('surveillance_speciale', '0002_listesurveillancespeciale_statut_archivee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheaptitude',
            name='ligne_surveillance_speciale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_aptitude', to='surveillance_speciale.lignesurveillancespeciale', verbose_name='Ligne surveillance médicale spéciale'),
        ),
    ]
