# Generated by Django 5.2.11 on 2026-05-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0031_ficheaptitude_ligne_surveillance_speciale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheaptitude',
            name='type_visite',
            field=models.CharField(choices=[('EMBAUCHE', "Visite d'Embauche"), ('PERIODIQUE', 'Visite Périodique'), ('REPRISE', 'Visite de Reprise'), ('SPONTANEE', 'Visite Spontanée'), ('SURVEILLANCE_SPECIALE', 'Surveillance médicale spéciale')], max_length=30, verbose_name='Type de visite'),
        ),
    ]
