# Generated by Django 5.2.11 on 2026-05-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0032_add_surveillance_speciale_type_visite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheaptitude',
            name='date_reprise',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Peut reprendre son travail à dater du'),
        ),
    ]
