# Generated by Django 5.2.11 on 2026-05-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0033_alter_ficheaptitude_date_reprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheaptitude',
            name='examens_ulterieurs',
            field=models.JSONField(blank=True, default=list, verbose_name='Examens médicaux ultérieurs (JSON)'),
        ),
        migrations.CreateModel(
            name='CertificatAptitudeMateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload Mateur (JSON)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('certificat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mateur_payload', to='medical_work.certificataptitude', verbose_name="Certificat d'Aptitude")),
            ],
            options={
                'verbose_name': "Certificat d'Aptitude (Mateur)",
                'verbose_name_plural': "Certificats d'Aptitude (Mateur)",
                'db_table': 'certificats_aptitude_mateur',
                'ordering': ['-date_modification'],
            },
        ),
    ]
