# Generated by Django 5.2.11 on 2026-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0034_ficheaptitude_examens_ulterieurs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificataptitudemateur',
            name='payload',
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='apc_accident_travail_sequelles',
            field=models.TextField(blank=True, default='', verbose_name='Accident travail avec séquelles'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='apc_maladie_professionnelle',
            field=models.TextField(blank=True, default='', verbose_name='Maladie professionnelle'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='apc_maladies_chroniques',
            field=models.TextField(blank=True, default='', verbose_name='Maladies chroniques'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='aptitude',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Aptitude'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='autres_remarques',
            field=models.TextField(blank=True, default='', verbose_name='Autres remarques'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='avis_assis_prolonge',
            field=models.TextField(blank=True, default='', verbose_name='Assis prolongé'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='avis_charge_sup_4kg',
            field=models.TextField(blank=True, default='', verbose_name='Charge > 4 kgr'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='avis_cou',
            field=models.TextField(blank=True, default='', verbose_name='Cou'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='avis_debout_prolonge',
            field=models.TextField(blank=True, default='', verbose_name='Debout prolongé'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='avis_effort_precision_concentration',
            field=models.TextField(blank=True, default='', verbose_name='Effort / précision / concentration'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='avis_etat_general_efficience',
            field=models.TextField(blank=True, default='', verbose_name='Etat général efficience'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='avis_poignet_bras_epaule',
            field=models.TextField(blank=True, default='', verbose_name='Poignet / Bras / Epaule'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='avis_rotation_equipe_possible',
            field=models.TextField(blank=True, default='', verbose_name='Rotation équipe possible'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='type_visite',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Type de visite'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_coupe_autres_remarques',
            field=models.TextField(blank=True, default='', verbose_name='Zone Coupe - Autres remarques'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_coupe_coupe',
            field=models.TextField(blank=True, default='', verbose_name='Zone Coupe - Coupe'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_coupe_sertissage_manuel',
            field=models.TextField(blank=True, default='', verbose_name='Zone Coupe - Sertissage manuel'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_montage_autre_postes',
            field=models.TextField(blank=True, default='', verbose_name='Zone Montage - Autre postes montage'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_montage_bol',
            field=models.TextField(blank=True, default='', verbose_name='Zone Montage - BOL'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_montage_c_agrafs',
            field=models.TextField(blank=True, default='', verbose_name='Zone Montage - C. Agrafs'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_montage_c_final',
            field=models.TextField(blank=True, default='', verbose_name='Zone Montage - C. Final'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_montage_goulotte',
            field=models.TextField(blank=True, default='', verbose_name='Zone Montage - Montage goulotte'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_montage_lad',
            field=models.TextField(blank=True, default='', verbose_name='Zone Montage - Montage LAD'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_montage_pu',
            field=models.TextField(blank=True, default='', verbose_name='Zone Montage - PU'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_montage_sous_element',
            field=models.TextField(blank=True, default='', verbose_name='Zone Montage - Sous élément'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_montage_vissage',
            field=models.TextField(blank=True, default='', verbose_name='Zone Montage - Vissage'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_prep_autres_remarques',
            field=models.TextField(blank=True, default='', verbose_name='Zone Préparation - Autres remarques'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_prep_eiamage',
            field=models.TextField(blank=True, default='', verbose_name='Zone Préparation - Eiamage'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_prep_epissure',
            field=models.TextField(blank=True, default='', verbose_name='Zone Préparation - Epissure'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_prep_kabatec',
            field=models.TextField(blank=True, default='', verbose_name='Zone Préparation - Kabatec'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_prep_lovage',
            field=models.TextField(blank=True, default='', verbose_name='Zone Préparation - Lovage'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_prep_retreint',
            field=models.TextField(blank=True, default='', verbose_name='Zone Préparation - Retreint'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='zone_prep_torsadage',
            field=models.TextField(blank=True, default='', verbose_name='Zone Préparation - Torsadage'),
        ),
    ]
