# Generated by Django 5.2.11 on 2026-05-06 16:20

import django.db.models.deletion
from django.db import migrations, models


def backfill_collab_medecin(apps, schema_editor):
    CertificatAptitudeMateur = apps.get_model("medical_work", "CertificatAptitudeMateur")
    CertificatAptitude = apps.get_model("medical_work", "CertificatAptitude")
    # backfill from certificat -> fiche_aptitude -> (collaborateur, medecin_travail)
    for row in CertificatAptitudeMateur.objects.select_related("certificat").all():
        cert = getattr(row, "certificat", None)
        if not cert:
            continue
        fiche = getattr(cert, "fiche_aptitude", None)
        if not fiche:
            try:
                fiche = CertificatAptitude.objects.select_related("fiche_aptitude").get(pk=cert.pk).fiche_aptitude
            except Exception:
                fiche = None
        if not fiche:
            continue
        updated = False
        if row.collaborateur_id is None and getattr(fiche, "collaborateur_id", None) is not None:
            row.collaborateur_id = fiche.collaborateur_id
            updated = True
        if row.medecin_travail_id is None and getattr(fiche, "medecin_travail_id", None) is not None:
            row.medecin_travail_id = fiche.medecin_travail_id
            updated = True
        if updated:
            row.save(update_fields=["collaborateur", "medecin_travail"])


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_mater_to_mateur'),
        ('employees', '0009_remove_collaborateur_cin_and_more'),
        ('medical_work', '0035_remove_certificataptitudemateur_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='collaborateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.collaborateur', verbose_name='Collaborateur'),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='medecin_travail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.medecin', verbose_name='Médecin du Travail'),
        ),
        migrations.RunPython(code=backfill_collab_medecin, reverse_code=migrations.RunPython.noop),
    ]
