# Generated by Django 5.2.11 on 2026-05-06 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_mater_to_mateur'),
        ('employees', '0009_remove_collaborateur_cin_and_more'),
        ('medical_work', '0036_certificataptitudemateur_collaborateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheSurveillanceSpecialeMateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_moins_18', models.BooleanField(default=False)),
                ('motif_enceinte_allaitante', models.BooleanField(default=False)),
                ('motif_handicape', models.BooleanField(default=False)),
                ('motif_travaux_risques_accidents', models.BooleanField(default=False)),
                ('motif_maladie_chronique', models.BooleanField(default=False)),
                ('motif_travaux_maladies_professionnelles', models.BooleanField(default=False)),
                ('poste_caracteristiques', models.TextField(blank=True, default='')),
                ('poste_ergonomie', models.TextField(blank=True, default='')),
                ('tache_habituelle', models.TextField(blank=True, default='')),
                ('risques_accidents', models.TextField(blank=True, default='')),
                ('tableaux_mp_et_agents', models.TextField(blank=True, default='')),
                ('evaluation_exposition', models.TextField(blank=True, default='')),
                ('surveillance_rows', models.JSONField(blank=True, default=list)),
                ('mesures_prevention', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('collaborateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_mateur_fiches', to='employees.collaborateur', verbose_name='Collaborateur')),
                ('fiche_aptitude', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_mateur', to='medical_work.ficheaptitude', verbose_name="Fiche d'aptitude (parent)")),
                ('medecin_travail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_mateur_fiches', to='account.medecin', verbose_name='Médecin du travail')),
            ],
            options={
                'verbose_name': 'Fiche SMS (Mateur)',
                'verbose_name_plural': 'Fiches SMS (Mateur)',
                'db_table': 'fiches_surveillance_speciale_mateur',
                'ordering': ['-date_creation'],
            },
        ),
    ]
