# Generated by Django 5.2.11 on 2026-05-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_work', '0037_fichesurveillancespecialemateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='entete_certificat_medical_aptitude',
            field=models.BooleanField(default=True, verbose_name="En-tête - Certificat médicale d'aptitude"),
        ),
        migrations.AddField(
            model_name='certificataptitudemateur',
            name='entete_reprise_au_poste',
            field=models.BooleanField(default=False, verbose_name='En-tête - Reprise au poste de travail'),
        ),
    ]
