# Generated by Django 5.2.11 on 2026-02-22 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_controle', models.CharField(max_length=50, unique=True, verbose_name='N° Contrôle')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name='Date émission')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='controles_medicaux/', verbose_name='Fichier PDF')),
                ('resultat', models.CharField(choices=[('VALIDE', 'Arrêt validé'), ('INVALIDE', 'Arrêt invalidé'), ('REDUIT', 'Arrêt réduit'), ('PROLONGE', 'Arrêt prolongé')], max_length=20, verbose_name='Résultat')),
                ('justification_medicale', models.TextField(verbose_name='Justification médicale')),
                ('nouvelle_date_fin_arret', models.DateField(blank=True, null=True, verbose_name='Nouvelle date fin arrêt')),
                ('envoye_rh', models.BooleanField(default=False, verbose_name='Envoyé au RH')),
                ('date_envoi_rh', models.DateTimeField(blank=True, null=True, verbose_name='Date envoi RH')),
            ],
            options={
                'verbose_name': 'Contrôle Médical',
                'verbose_name_plural': 'Contrôles Médicaux',
                'db_table': 'controles_medicaux',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='ContreVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(verbose_name='N°')),
                ('matricule', models.CharField(max_length=50, verbose_name='Matricule')),
                ('docteur', models.CharField(max_length=200, verbose_name='Docteur')),
                ('nom_prenom', models.CharField(max_length=255, verbose_name='Nom & Prénom')),
                ('duree_repos', models.PositiveIntegerField(verbose_name='Durée repos (jours)')),
                ('date_debut', models.DateField(verbose_name='À partir')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque')),
                ('date_visite', models.DateField(verbose_name='Date')),
                ('date_heure_visite', models.DateTimeField(verbose_name='Date et heure visite')),
                ('lieu_visite', models.TextField(verbose_name='Lieu de visite')),
                ('observations_cliniques', models.TextField(blank=True, verbose_name='Observations cliniques')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('tension_arterielle', models.CharField(blank=True, max_length=20, verbose_name='Tension artérielle')),
                ('avis', models.CharField(choices=[('JUSTIFIE', 'Arrêt justifié'), ('NON_JUSTIFIE', 'Arrêt non justifié'), ('A_REDUIRE', 'Arrêt à réduire'), ('A_PROLONGER', 'Arrêt à prolonger')], default='JUSTIFIE', max_length=20, verbose_name='Avis')),
                ('nouvelle_date_fin', models.DateField(blank=True, null=True, verbose_name='Nouvelle date fin (si modifié)')),
                ('justification_medicale', models.TextField(verbose_name='Justification médicale')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contre_visites', to='employees.collaborateur', verbose_name='Collaborateur')),
            ],
            options={
                'verbose_name': 'Contre-Visite',
                'verbose_name_plural': 'Contre-Visites',
                'db_table': 'contre_visites',
                'ordering': ['-date_visite', 'numero_ordre'],
            },
        ),
    ]
