# Generated by Django 5.2.11 on 2026-02-22 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('control_visits', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrevisite',
            name='item_passage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contre_visite', to='planning.itempassage', verbose_name='Item de passage'),
        ),
        migrations.AddField(
            model_name='contrevisite',
            name='medecin_controleur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contre_visites_effectuees', to='account.medecin', verbose_name='Médecin contrôleur'),
        ),
        migrations.AddField(
            model_name='controlemedical',
            name='contre_visite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controle_medical', to='control_visits.contrevisite', verbose_name='Contre-visite'),
        ),
    ]
