# Generated by Django 5.2.11 on 2026-02-22 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_visits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlemedical',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlemedical',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='controlemedical',
            name='email_rh',
            field=models.EmailField(blank=True, help_text='Email du destinataire RH', max_length=254, verbose_name='Email RH'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='avis',
            field=models.CharField(choices=[('JUSTIFIE', 'Arrêt justifié (maintenir)'), ('NON_JUSTIFIE', 'Arrêt non justifié (invalider)'), ('A_REDUIRE', 'Arrêt à réduire'), ('A_PROLONGER', 'Arrêt à prolonger')], help_text='Décision du médecin contrôleur', max_length=20, verbose_name='Avis'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='date_debut',
            field=models.DateField(help_text="Date de début de l'arrêt", verbose_name='À partir'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='date_heure_visite',
            field=models.DateTimeField(help_text='Date et heure exacte de la contre-visite', verbose_name='Date et heure visite'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='date_visite',
            field=models.DateField(help_text='Date de la contre-visite (pour Excel)', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='docteur',
            field=models.CharField(help_text='Nom du médecin contrôleur (copié pour Excel)', max_length=200, verbose_name='Docteur'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='duree_repos',
            field=models.PositiveIntegerField(help_text="Durée initiale de l'arrêt en jours", verbose_name='Durée repos (jours)'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='justification_medicale',
            field=models.TextField(help_text='Justification détaillée de la décision', verbose_name='Justification médicale'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='lieu_visite',
            field=models.TextField(help_text="Adresse où s'est déroulée la visite", verbose_name='Lieu de visite'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='matricule',
            field=models.CharField(help_text='Matricule du collaborateur (copié pour Excel)', max_length=50, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='nom_prenom',
            field=models.CharField(help_text='Nom complet du collaborateur (copié pour Excel)', max_length=255, verbose_name='Nom & Prénom'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='nouvelle_date_fin',
            field=models.DateField(blank=True, help_text="Nouvelle date de fin si l'arrêt est modifié (réduit ou prolongé)", null=True, verbose_name='Nouvelle date fin'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='numero_ordre',
            field=models.PositiveIntegerField(help_text="Numéro d'ordre dans la liste (ex: 1, 2, 3...)", verbose_name='N°'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='observations_cliniques',
            field=models.TextField(blank=True, help_text='Observations détaillées du médecin contrôleur', verbose_name='Observations cliniques'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='remarque',
            field=models.TextField(blank=True, help_text='Remarque visible dans le tableau Excel', verbose_name='Remarque'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Température corporelle en degrés Celsius', max_digits=4, null=True, verbose_name='Température (°C)'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='tension_arterielle',
            field=models.CharField(blank=True, help_text='Ex: 12/8', max_length=20, verbose_name='Tension artérielle'),
        ),
        migrations.AlterField(
            model_name='controlemedical',
            name='date_emission',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name="Date d'émission"),
        ),
        migrations.AlterField(
            model_name='controlemedical',
            name='date_envoi_rh',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi au RH"),
        ),
        migrations.AlterField(
            model_name='controlemedical',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Document PDF généré', null=True, upload_to='controles_medicaux/%Y/%m/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='controlemedical',
            name='justification_medicale',
            field=models.TextField(help_text='Justification détaillée du résultat', verbose_name='Justification médicale'),
        ),
        migrations.AlterField(
            model_name='controlemedical',
            name='nouvelle_date_fin_arret',
            field=models.DateField(blank=True, help_text="Nouvelle date de fin si l'arrêt a été modifié", null=True, verbose_name='Nouvelle date fin arrêt'),
        ),
        migrations.AlterField(
            model_name='controlemedical',
            name='numero_controle',
            field=models.CharField(help_text='Numéro unique du contrôle médical (ex: CM-2026-001)', max_length=50, unique=True, verbose_name='N° Contrôle'),
        ),
        migrations.AlterField(
            model_name='controlemedical',
            name='resultat',
            field=models.CharField(choices=[('VALIDE', 'Arrêt validé (maintenu)'), ('INVALIDE', 'Arrêt invalidé'), ('REDUIT', 'Arrêt réduit'), ('PROLONGE', 'Arrêt prolongé')], help_text='Résultat officiel du contrôle', max_length=20, verbose_name='Résultat'),
        ),
    ]
