# Generated by Django 5.2.11 on 2026-02-22 20:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('control_visits', '0003_controlemedical_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrevisite',
            options={'ordering': ['-date', 'numero_ordre'], 'verbose_name': 'Contre-Visite', 'verbose_name_plural': 'Contre-Visites'},
        ),
        migrations.RenameField(
            model_name='contrevisite',
            old_name='date_debut',
            new_name='a_partir',
        ),
        migrations.RemoveField(
            model_name='contrevisite',
            name='avis',
        ),
        migrations.RemoveField(
            model_name='contrevisite',
            name='collaborateur',
        ),
        migrations.RemoveField(
            model_name='contrevisite',
            name='date_heure_visite',
        ),
        migrations.RemoveField(
            model_name='contrevisite',
            name='date_visite',
        ),
        migrations.RemoveField(
            model_name='contrevisite',
            name='item_passage',
        ),
        migrations.RemoveField(
            model_name='contrevisite',
            name='justification_medicale',
        ),
        migrations.RemoveField(
            model_name='contrevisite',
            name='lieu_visite',
        ),
        migrations.RemoveField(
            model_name='contrevisite',
            name='nouvelle_date_fin',
        ),
        migrations.RemoveField(
            model_name='contrevisite',
            name='observations_cliniques',
        ),
        migrations.RemoveField(
            model_name='contrevisite',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='contrevisite',
            name='tension_arterielle',
        ),
        migrations.AddField(
            model_name='contrevisite',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date de la contre-visite', verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='docteur',
            field=models.CharField(help_text='Nom du médecin contrôleur (ex: Dr. Mejri)', max_length=200, verbose_name='Docteur'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='duree_repos',
            field=models.PositiveIntegerField(help_text='Durée en jours (ex: 20)', verbose_name='Durée de repos'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='matricule',
            field=models.CharField(help_text='Matricule du collaborateur (ex: EMP001)', max_length=50, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='medecin_controleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contre_visites', to='account.medecin', verbose_name='Médecin contrôleur'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='nom_prenom',
            field=models.CharField(help_text='Nom complet du collaborateur', max_length=255, verbose_name='Nom et Prénom'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='numero_ordre',
            field=models.PositiveIntegerField(help_text="Numéro d'ordre (1, 2, 3...)", verbose_name='N°'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='remarque',
            field=models.TextField(blank=True, help_text='Remarque ou observation', verbose_name='Remarque'),
        ),
    ]
