# Generated by Django 5.2.11 on 2026-02-22 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_visits', '0004_alter_contrevisite_options_and_more'),
        ('planning', '0002_alter_itempassage_collaborateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrevisite',
            name='item_passage',
            field=models.OneToOneField(blank=True, help_text='Optionnel : lien vers la liste de passage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contre_visite', to='planning.itempassage', verbose_name='Item de passage'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='docteur',
            field=models.CharField(help_text='Nom du médecin contrôleur', max_length=200, verbose_name='Docteur'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='duree_repos',
            field=models.PositiveIntegerField(help_text='Durée en jours', verbose_name='Durée de repos'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='matricule',
            field=models.CharField(help_text='Matricule du collaborateur', max_length=50, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='remarque',
            field=models.TextField(blank=True, help_text='Remarque du médecin', verbose_name='Remarque'),
        ),
    ]
