# Generated by Django 5.2.11 on 2026-02-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_visits', '0005_contrevisite_item_passage_alter_contrevisite_docteur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlemedical',
            name='email_rh',
        ),
        migrations.RemoveField(
            model_name='controlemedical',
            name='justification_medicale',
        ),
        migrations.RemoveField(
            model_name='controlemedical',
            name='nouvelle_date_fin_arret',
        ),
        migrations.RemoveField(
            model_name='controlemedical',
            name='resultat',
        ),
        migrations.AddField(
            model_name='controlemedical',
            name='avis_medecin_controleur',
            field=models.TextField(default='À compléter', help_text='Avis médical détaillé', verbose_name='Avis du médecin contrôleur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlemedical',
            name='cachet_signature',
            field=models.ImageField(blank=True, help_text='Image du cachet et signature du médecin', null=True, upload_to='cachets_signatures/%Y/%m/', verbose_name='Cachet et signature'),
        ),
        migrations.AddField(
            model_name='controlemedical',
            name='matricule',
            field=models.CharField(default='', help_text='Matricule du collaborateur', max_length=50, verbose_name='Matricule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlemedical',
            name='nom',
            field=models.CharField(default='', help_text='Nom du collaborateur', max_length=150, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlemedical',
            name='prenom',
            field=models.CharField(default='', help_text='Prénom du collaborateur', max_length=150, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlemedical',
            name='repos_prescrit',
            field=models.CharField(default='', help_text='Ex: 20 jours à partir du 02/01/2026', max_length=200, verbose_name='Repos prescrit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlemedical',
            name='segment',
            field=models.CharField(default='', help_text='Segment/Département du collaborateur', max_length=100, verbose_name='Segment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlemedical',
            name='numero_controle',
            field=models.CharField(help_text='Numéro unique (ex: CM-2026-001)', max_length=50, unique=True, verbose_name='N° Contrôle'),
        ),
    ]
