# Generated by Django 5.2.11 on 2026-02-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_visits', '0006_remove_controlemedical_email_rh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrevisite',
            name='docteur',
        ),
        migrations.RemoveField(
            model_name='controlemedical',
            name='cachet_signature',
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='numero_ordre',
            field=models.PositiveIntegerField(editable=False, help_text='Auto-généré', verbose_name='N°'),
        ),
    ]
