# Generated by Django 5.2.11 on 2026-03-09 16:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_create_groups_and_permissions'),
        ('control_visits', '0007_remove_contrevisite_docteur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlemedical',
            name='fichier_pdf',
        ),
        migrations.CreateModel(
            name='DemandeExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('dr', models.TextField(verbose_name='Docteur destinataire')),
                ('date_demande', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de demande')),
                ('collaborateur_nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('collaborateur_prenom', models.CharField(max_length=255, verbose_name='Prenom')),
                ('collaborateur_matricule', models.CharField(max_length=50, verbose_name='Matricule')),
                ('pieces_jointes', models.TextField(blank=True, verbose_name='Pieces jointes')),
                ('poste', models.CharField(blank=True, max_length=255, verbose_name='Poste')),
                ('autres_missions', models.TextField(blank=True, verbose_name='Autres missions')),
                ('contre_visite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_expertise', to='control_visits.contrevisite', verbose_name='Contre-visite')),
                ('medecin_controleur', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_expertise', to='account.medecin', verbose_name='Medecin controleur')),
            ],
            options={
                'verbose_name': 'Demande d expertise',
                'verbose_name_plural': 'Demandes d expertise',
                'ordering': ['-date_demande'],
            },
        ),
    ]
