# Generated by Django 5.2.11 on 2026-03-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_visits', '0008_remove_controlemedical_fichier_pdf_demandeexpertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrevisite',
            name='repos_initial',
            field=models.PositiveIntegerField(blank=True, help_text='Durée de repos initialement prescrite par le médecin traitant (en jours)', null=True, verbose_name='Repos initial (médecin traitant)'),
        ),
        migrations.AlterField(
            model_name='contrevisite',
            name='duree_repos',
            field=models.PositiveIntegerField(help_text='Durée en jours (validée par le médecin contrôleur)', verbose_name='Durée de repos'),
        ),
    ]
