# Generated by Django 5.2.11 on 2026-04-09 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_site_medecin_site'),
        ('control_visits', '0010_contrevisite_refus_repos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrevisite',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contre_visites', to='account.site', verbose_name='Site'),
        ),
    ]
