# Generated by Django 5.2.11 on 2026-05-01 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_site_nature_activite_site_numero_cnss_and_more'),
        ('control_visits', '0011_contrevisite_site'),
        ('employees', '0009_remove_collaborateur_cin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeContreVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_visite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('EN_TRAITEMENT', 'En traitement'), ('CLOTUREE', 'Cloturee')], default='BROUILLON', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listes_contre_visites_creees', to='account.profile')),
                ('medecin_controleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listes_contre_visites_assignees', to='account.medecin')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listes_contre_visites', to='account.site')),
            ],
            options={
                'verbose_name': 'Liste contre-visite',
                'verbose_name_plural': 'Listes contre-visites',
                'db_table': 'listes_contre_visites',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneContreVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(blank=True, null=True)),
                ('presence', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('REPORTE', 'Reporte')], default='EN_ATTENTE', max_length=20)),
                ('raison_report', models.TextField(blank=True)),
                ('verdict_saisi', models.BooleanField(default=False)),
                ('collaborateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.collaborateur')),
                ('contre_visite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne', to='control_visits.contrevisite')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='control_visits.listecontrevisite')),
            ],
            options={
                'verbose_name': 'Ligne contre-visite',
                'verbose_name_plural': 'Lignes contre-visites',
                'db_table': 'lignes_contre_visites',
                'ordering': ['ordre'],
            },
        ),
    ]
