# Generated by Django 5.2.11 on 2026-05-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_visits', '0014_ligne_cv_ordre_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignecontrevisite',
            options={'ordering': ['ordre', 'pk'], 'verbose_name': 'Ligne contre-visite', 'verbose_name_plural': 'Lignes contre-visites'},
        ),
        migrations.AlterField(
            model_name='lignecontrevisite',
            name='sms_jour_j_envoye',
            field=models.BooleanField(default=False, verbose_name='SMS jour J (file) envoyé'),
        ),
    ]
