# Generated by Django 5.2.11 on 2026-03-08 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		("employees", "0005_collaborateur_numero_cnss"),
	]

	operations = [
		migrations.CreateModel(
			name="AccidentTravail",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("date_creation", models.DateTimeField(auto_now_add=True, editable=False)),
				("date_accident", models.DateField()),
				("heure_accident", models.TimeField(blank=True, null=True)),
				(
					"type_accident",
					models.CharField(
						choices=[("TRAVAIL", "Travail"), ("TRAJET", "Trajet")],
						max_length=20,
					),
				),
				("lieu_accident", models.CharField(max_length=255)),
				("description", models.TextField()),
				("siege_lesion", models.CharField(max_length=255)),
				(
					"nature_lesion",
					models.CharField(
						choices=[
							("TRAUMATISME", "Traumatisme"),
							("BRULURE", "Brulure"),
							("COUPURE", "Coupure"),
							("AUTRE", "Autre"),
						],
						max_length=20,
					),
				),
				("cause_accident", models.CharField(max_length=255)),
				("agent_materiel", models.CharField(blank=True, max_length=255)),
				("temoins", models.TextField(blank=True)),
				("repos_initial", models.PositiveIntegerField(default=0)),
				("prolongation", models.PositiveIntegerField(default=0)),
				("criticite", models.CharField(blank=True, max_length=100)),
				("reprise_medecin_travail", models.DateField(blank=True, null=True)),
				("date_declaration_service_medical", models.DateField()),
				("date_sortie_declaration", models.DateField(blank=True, null=True)),
				("chauffeur_sortie", models.CharField(blank=True, max_length=255)),
				("reporting_interne", models.BooleanField(default=False)),
				("reporting_wsd", models.BooleanField(default=False)),
				(
					"collaborateur",
					models.ForeignKey(
						on_delete=django.db.models.deletion.PROTECT,
						related_name="accidents_travail",
						to="employees.collaborateur",
					),
				),
				(
					"infirmiere",
					models.ForeignKey(
						editable=False,
						on_delete=django.db.models.deletion.PROTECT,
						related_name="accidents_saisis",
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
			options={
				"verbose_name": "Accident de travail",
				"verbose_name_plural": "Accidents de travail",
				"ordering": ["-date_accident", "-date_creation"],
			},
		),
	]
