# Generated by Django 5.2.11 on 2026-03-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_infirmier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidenttravail',
            name='num_cnam',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='accidenttravail',
            name='plant_section',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='accidenttravail',
            name='nature_lesion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accidenttravail',
            name='type_accident',
            field=models.TextField(),
        ),
    ]
