# Generated by Django 5.2.11 on 2026-03-08 00:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_infirmier', '0002_accidenttravail_num_cnam_and_more'),
        ('employees', '0005_collaborateur_numero_cnss'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaladieProfessionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_section', models.CharField(blank=True, max_length=150)),
                ('segment', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mois', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('date_debut_maladie', models.DateField()),
                ('maladie', models.CharField(max_length=255)),
                ('code_tableau_cnam', models.CharField(max_length=50)),
                ('cause', models.CharField(max_length=255)),
                ('nature_travail', models.CharField(max_length=255)),
                ('changement_poste', models.BooleanField(default=False)),
                ('ancien_poste', models.CharField(blank=True, max_length=255)),
                ('nouveau_poste', models.CharField(blank=True, max_length=255)),
                ('decision_medecin', models.CharField(max_length=255)),
                ('repos_initial', models.PositiveIntegerField(default=0)),
                ('prolongation', models.PositiveIntegerField(default=0)),
                ('rechute', models.PositiveIntegerField(default=0)),
                ('reprise_medecin_traitant', models.BooleanField(default=False)),
                ('reprise_medecin_travail', models.DateField(blank=True, null=True)),
                ('date_declaration_service_medical', models.DateField()),
                ('date_sortie_declaration', models.CharField(blank=True, max_length=255)),
                ('chauffeur_sortie', models.CharField(blank=True, max_length=255)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maladies_professionnelles', to='employees.collaborateur')),
                ('infirmiere', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='maladies_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maladie professionnelle',
                'verbose_name_plural': 'Maladies professionnelles',
                'ordering': ['-date_debut_maladie', '-date_creation'],
            },
        ),
    ]
