# Generated by Django 5.2.11 on 2026-03-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_infirmier', '0003_maladieprofessionnelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='anciennete',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancienneté'),
        ),
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='repos_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='accidenttravail',
            name='num_cnam',
            field=models.CharField(blank=True, max_length=50, verbose_name='N°01'),
        ),
        migrations.AlterField(
            model_name='accidenttravail',
            name='type_accident',
            field=models.TextField(verbose_name='Accident du trajet'),
        ),
    ]
