# Generated by Django 5.2.11 on 2026-03-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_infirmier', '0004_maladieprofessionnelle_anciennete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidenttravail',
            name='total_jour_perdu',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
