# Generated by Django 5.2.11 on 2026-03-11 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_infirmier', '0005_accidenttravail_total_jour_perdu'),
        ('employees', '0006_collaborateur_plant_section_collaborateur_segment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentAvecBon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bon', models.DateField(verbose_name='Date du bon')),
                ('numero_assurance', models.CharField(max_length=100, verbose_name='N° Assurance / CNAM')),
                ('date_incident', models.DateField(verbose_name="Date de l'incident")),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('cause', models.CharField(max_length=255, verbose_name='Cause')),
                ('lesion', models.TextField(verbose_name='Lésion / Description de la blessure')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents_avec_bon', to='employees.collaborateur')),
                ('infirmiere', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_avec_bon_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident avec bon de sortie',
                'verbose_name_plural': 'Incidents avec bon de sortie',
                'ordering': ['-date_bon', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='IncidentSansBon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(blank=True, max_length=150, verbose_name='Segment')),
                ('plant_section', models.CharField(blank=True, max_length=150, verbose_name='Plant/Section')),
                ('date_incident', models.DateField(verbose_name="Date de l'incident")),
                ('heure_incident', models.TimeField(verbose_name="Heure d'arrivée à l'infirmerie")),
                ('mode_lesion', models.TextField(verbose_name='Mode de lésion')),
                ('agent_causal', models.CharField(max_length=255, verbose_name='Agent causal')),
                ('remarque', models.TextField(blank=True, verbose_name='Remarque / Soin effectué')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents_sans_bon', to='employees.collaborateur')),
                ('infirmiere', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_sans_bon_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident sans bon de sortie',
                'verbose_name_plural': 'Incidents sans bon de sortie',
                'ordering': ['-date_incident', '-date_creation'],
            },
        ),
    ]
