# Generated by Django 5.2.11 on 2026-03-11 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_infirmier', '0006_incidentavecbon_incidentsansbon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentavecbon',
            name='numero_assurance',
        ),
        migrations.AddField(
            model_name='incidentavecbon',
            name='incident_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_sortie', to='act_infirmier.incidentsansbon', verbose_name='Incident sans bon (origine)'),
        ),
        migrations.AddField(
            model_name='incidentavecbon',
            name='num_assurance',
            field=models.CharField(default=1, max_length=100, verbose_name='N° Assurance / CNAM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentavecbon',
            name='plant_section',
            field=models.CharField(blank=True, max_length=150, verbose_name='Plant/Section'),
        ),
        migrations.AddField(
            model_name='incidentavecbon',
            name='segment',
            field=models.CharField(blank=True, max_length=150, verbose_name='Segment'),
        ),
    ]
