# Generated by Django 5.2.11 on 2026-03-11 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("act_infirmier", "0007_incidentavecbon_updates"),
        ("employees", "0006_collaborateur_plant_section_collaborateur_segment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclarationCNAM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("matricule_cnss", models.CharField(blank=True, editable=False, max_length=50)),
                ("type_accident", models.CharField(max_length=255)),
                ("date_accident", models.DateField()),
                ("chauffeur", models.CharField(max_length=255)),
                ("date_collecte_chauffeur", models.DateField(blank=True, null=True)),
                ("date_cachet_cnam", models.DateField(blank=True, null=True)),
                ("date_limite_declaration", models.DateField(blank=True, null=True)),
                ("nb_jours_retard", models.IntegerField(default=0, editable=False)),
                ("cause_retard", models.TextField(blank=True)),
                ("commentaire", models.TextField(blank=True)),
                ("actions", models.TextField(blank=True)),
                ("correction", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True, editable=False)),
                (
                    "collaborateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="declarations_cnam",
                        to="employees.collaborateur",
                    ),
                ),
                (
                    "infirmiere",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="declarations_cnam_saisies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Declaration CNAM",
                "verbose_name_plural": "Declarations CNAM",
                "ordering": ["-date_accident", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="TransfertUrgence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("heure", models.CharField(max_length=20)),
                ("chauffeur", models.CharField(max_length=255, verbose_name="Nom & Prenom du chauffeur")),
                ("depart", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("num_ordre", models.PositiveIntegerField(unique=True, verbose_name="N Ordre de Transport")),
                ("plant", models.CharField(max_length=150)),
                ("frais_deplacement", models.DecimalField(decimal_places=2, default="0.00", max_digits=10)),
                ("cost_center", models.CharField(max_length=150)),
                ("date_creation", models.DateTimeField(auto_now_add=True, editable=False)),
                (
                    "collaborateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_urgence",
                        to="employees.collaborateur",
                    ),
                ),
                (
                    "infirmiere",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_urgence_saisis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfert urgence",
                "verbose_name_plural": "Transferts urgence",
                "ordering": ["-date", "-date_creation"],
            },
        ),
    ]
