# Generated by Django 5.2.11 on 2026-03-11 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_medecin_heures_par_defaut'),
        ('act_infirmier', '0008_transferturgence_declarationcnam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('motif', models.TextField(blank=True)),
                ('mois', models.PositiveIntegerField(editable=False)),
                ('annee', models.PositiveIntegerField(editable=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('infirmiere', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='absences_medecin_saisies', to=settings.AUTH_USER_MODEL)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='account.medecin')),
            ],
            options={
                'verbose_name': 'Absence médecin',
                'verbose_name_plural': 'Absences médecins',
                'ordering': ['-date'],
                'unique_together': {('medecin', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PointageMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heures_travaillees', models.PositiveIntegerField(default=2)),
                ('remarque', models.TextField(blank=True)),
                ('mois', models.PositiveIntegerField(editable=False)),
                ('annee', models.PositiveIntegerField(editable=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('infirmiere', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='pointages_medecin_saisis', to=settings.AUTH_USER_MODEL)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointages', to='account.medecin')),
            ],
            options={
                'verbose_name': 'Pointage médecin',
                'verbose_name_plural': 'Pointages médecins',
                'ordering': ['-date'],
                'unique_together': {('medecin', 'date')},
            },
        ),
    ]
