# Generated by Django 5.2.11 on 2026-03-11 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_medecin_heures_par_defaut'),
        ('act_infirmier', '0009_pointagemedecin_absencemedecin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True, verbose_name='Motif du transfert')),
                ('accompagnant', models.CharField(blank=True, max_length=200, verbose_name='Accompagnant')),
                ('moyen_transport', models.CharField(blank=True, max_length=100, verbose_name='Moyen de transport')),
                ('montant_prime', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Montant prime')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('infirmier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_transport_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Infirmier/ère')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_transport', to='account.medecin', verbose_name='Médecin prescripteur')),
                ('transfert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordre_transport', to='act_infirmier.transferturgence', verbose_name="Transfert d'urgence")),
            ],
            options={
                'verbose_name': 'Ordre de transport',
                'verbose_name_plural': 'Ordres de transport',
                'ordering': ['-transfert__date', '-date_creation'],
            },
        ),
    ]
