# Generated by Django 5.2.11 on 2026-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_infirmier', '0010_ordretransport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferturgence',
            name='num_ordre',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='N Ordre de Transport'),
        ),
    ]
