# Generated by Django 5.2.11 on 2026-03-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_infirmier', '0014_documentmedicalscanne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmedicalscanne',
            name='matricule_ref',
            field=models.CharField(blank=True, help_text='Obligatoire si pas de collaborateur (ex. candidat embauche non encore créé).', max_length=50, verbose_name='Matricule (candidat / référence)'),
        ),
    ]
