# Generated by Django 5.2.11 on 2026-04-07 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_infirmier', '0015_alter_documentmedicalscanne_matricule_ref'),
        ('employees', '0009_remove_collaborateur_cin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaladieChronique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(blank=True, max_length=150, verbose_name='Segment')),
                ('date_declaration', models.DateField(verbose_name='Date de déclaration')),
                ('type_maladie', models.CharField(choices=[('Diabète', 'Diabète'), ('Hypertension', 'Hypertension'), ('Asthme', 'Asthme'), ('Insuffisance rénale', 'Insuffisance rénale'), ('Épilepsie', 'Épilepsie'), ('Autre', 'Autre')], max_length=50, verbose_name='Type de maladie')),
                ('type_maladie_autre', models.CharField(blank=True, max_length=255, verbose_name='Type de maladie (autre)')),
                ('num_tel', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maladies_chroniques', to='employees.collaborateur')),
                ('infirmiere', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='maladies_chroniques_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maladie chronique',
                'verbose_name_plural': 'Maladies chroniques',
                'ordering': ['-date_declaration'],
            },
        ),
        migrations.CreateModel(
            name='RendezVousPsychologue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(blank=True, max_length=150, verbose_name='Segment')),
                ('service', models.CharField(blank=True, max_length=150, verbose_name='Service')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Position/Poste/Fonction')),
                ('site', models.CharField(blank=True, max_length=150, verbose_name='Site')),
                ('superieur_hierarchique', models.CharField(blank=True, max_length=200, verbose_name='Supérieur hiérarchique')),
                ('num_tel', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('date_rdv', models.DateField(verbose_name='Date du rendez-vous')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdv_psychologue', to='employees.collaborateur')),
                ('infirmiere', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='rdv_psychologue_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RDV Psychologue du travail',
                'verbose_name_plural': 'RDV Psychologues du travail',
                'ordering': ['-date_rdv'],
            },
        ),
        migrations.CreateModel(
            name='RendezVousSagefemme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(blank=True, max_length=150, verbose_name='Segment')),
                ('site', models.CharField(blank=True, max_length=150, verbose_name='Site')),
                ('num_tel', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('date_rdv', models.DateField(verbose_name='Date du rendez-vous')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rdv_sagefemme', to='employees.collaborateur')),
                ('infirmiere', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='rdv_sagefemme_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RDV Sage-femme',
                'verbose_name_plural': 'RDV Sages-femmes',
                'ordering': ['-date_rdv'],
            },
        ),
    ]
