# Generated by Django 5.2.11 on 2026-04-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_infirmier', '0016_maladiechronique_rendezvouspsychologue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvoussagefemme',
            name='motif_rdv',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motif du rendez-vous'),
        ),
    ]
