# Generated by Django 5.2.11 on 2026-04-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_infirmier', '0019_rendezvouspsychologue_secteur_collaborateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maladieprofessionnelle',
            name='is_tms',
            field=models.BooleanField(default=False, verbose_name='Trouble Musculo-Squelettique (TMS)'),
        ),
    ]
