# Generated by Django 5.2.11 on 2026-05-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_infirmier', '0021_transferturgence_telephone_chauffeur_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidenttravail',
            name='criticite',
            field=models.CharField(blank=True, choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé')], max_length=20, verbose_name='Criticité'),
        ),
        migrations.AlterField(
            model_name='accidenttravail',
            name='plant_section',
            field=models.CharField(blank=True, help_text='Zone ou section d’usine concernée par l’accident.', max_length=150, verbose_name='Plant / section'),
        ),
    ]
