# Generated by Django 5.2.11 on 2026-02-25 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_collaborateur_photo'),
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='antecedents',
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='antecedents_chirurgicaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='antecedents_familiaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='antecedents_gyneco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='antecedents_medicaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='autres_vaccins',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='nom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dossiers/photos/'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='prenom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='vaccin_hepatite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='vaccin_tetanos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='vaccin_tuberculose',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='collaborateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_medicaux', to='employees.collaborateur'),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
    ]
