# Generated by Django 5.2.11 on 2026-02-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_remove_dossiermedical_antecedents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='alcool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='automedication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='tabac',
            field=models.BooleanField(default=False),
        ),
    ]
