# Generated by Django 5.2.11 on 2026-02-25 14:52

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def deduplicate_dossier_collaborateur(apps, schema_editor):
    DossierMedical = apps.get_model('medical_records', 'DossierMedical')

    duplicates = (
        DossierMedical.objects
        .exclude(collaborateur__isnull=True)
        .values('collaborateur_id')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )

    for row in duplicates:
        dossiers = (
            DossierMedical.objects
            .filter(collaborateur_id=row['collaborateur_id'])
            .order_by('-date_modification', '-date_creation', '-id')
        )
        keep = dossiers.first()
        if keep:
            dossiers.exclude(id=keep.id).update(collaborateur=None)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_collaborateur_photo'),
        ('medical_records', '0003_dossiermedical_alcool_dossiermedical_automedication_and_more'),
    ]

    operations = [
        migrations.RunPython(deduplicate_dossier_collaborateur, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dossiermedical',
            name='collaborateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_medical', to='employees.collaborateur'),
        ),
    ]
