# Generated by Django 5.2.11 on 2026-03-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_alter_dossiermedical_collaborateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='matricule_ref',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricule de reference'),
        ),
    ]
