# Generated by Django 5.2.11 on 2026-02-26 22:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_create_groups_and_permissions'),
        ('planning', '0003_alter_listepassage_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('diagnostic', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('item_passage', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='planning.itempassage')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations_effectuees', to='account.medecin')),
            ],
            options={
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='CertificatMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('nom_prenom_medecin', models.CharField(blank=True, max_length=200)),
                ('nom_prenom_collab', models.CharField(blank=True, max_length=200)),
                ('jours_repos', models.PositiveIntegerField()),
                ('date_debut_repos', models.DateField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='consultations.consultation')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicaments', models.TextField()),
                ('date_emission', models.DateField(default=datetime.date.today)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='consultations.consultation')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
    ]
