# Generated by Django 5.2.11 on 2026-03-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_update_medicament_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='consultations.consultation'),
        ),
    ]
