# Generated by Django 5.2.11 on 2026-03-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_alter_ordonnance_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneordonnance',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('DONNEE', 'Donnée'), ('PHARMACIE', 'Pharmacie'), ('IGNORE', 'Ignorée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
