# Generated by Django 5.2.11 on 2026-03-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_alter_ligneordonnance_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosologieStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(help_text='Ex: 3 fois par jour — matin, midi et soir — pendant 7 jours', max_length=255, unique=True, verbose_name='Texte de posologie')),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Les posologies avec le plus petit numéro apparaissent en premier', verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour masquer sans supprimer', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Posologie standard',
                'verbose_name_plural': 'Posologies standard',
                'ordering': ['ordre', 'texte'],
            },
        ),
    ]
