# Generated by Django 5.2.11 on 2026-04-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_posologiestandard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatAptitudeGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom_patient', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('est_bonne_sante', models.BooleanField(default=False)),
                ('indemne_pathologie_contagieuse', models.BooleanField(default=False)),
                ('apte_sport', models.BooleanField(default=False)),
                ('apte_collectivite', models.BooleanField(default=False)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats_aptitude_generale', to='consultations.consultation')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='CertificatBonneSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom_enfant', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('correctement_vaccine', models.BooleanField(default=False)),
                ('indemne_maladies_contagieuses', models.BooleanField(default=False)),
                ('apte_collectivite', models.BooleanField(default=False)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats_bonne_sante', to='consultations.consultation')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='CertificatExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_patient', models.CharField(max_length=200)),
                ('type_exemption', models.CharField(max_length=255)),
                ('duree_exemption', models.CharField(max_length=100)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats_exemption', to='consultations.consultation')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='CertificatPermisConduire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('cin', models.CharField(max_length=50)),
                ('cin_delivree_a', models.CharField(max_length=200)),
                ('cin_date', models.DateField()),
                ('groupe_permis', models.CharField(choices=[('groupe_1', 'Groupe 1'), ('groupe_2', 'Groupe 2'), ('les_deux', 'Les deux')], max_length=20)),
                ('categories', models.TextField(help_text='Catégories demandées: A1, A, B, C, D...')),
                ('decision', models.CharField(choices=[('apte', 'Apte'), ('apte_avec_conditions', 'Apte avec conditions'), ('inapte', 'Inapte'), ('renvoyer_specialiste', 'Renvoyer à un spécialiste')], max_length=30)),
                ('specialite_renvoi', models.CharField(blank=True, max_length=200)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats_permis', to='consultations.consultation')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='CertificatPrenuptial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('cin', models.CharField(max_length=50)),
                ('groupe_sanguin_fait', models.BooleanField(default=False)),
                ('hepatite_b_fait', models.BooleanField(default=False)),
                ('hepatite_c_fait', models.BooleanField(default=False)),
                ('radio_thorax_fait', models.BooleanField(default=False)),
                ('autres_examens', models.TextField(blank=True)),
                ('informe_resultats', models.BooleanField(default=False)),
                ('conseille_hepatite_b', models.BooleanField(default=False)),
                ('conseil_genetique', models.BooleanField(default=False)),
                ('planification_naissance', models.BooleanField(default=False)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats_prenuptiaux', to='consultations.consultation')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
    ]
