# Generated by Django 5.2.11 on 2026-04-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_certificataptitudegenerale_certificatbonnesante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificataptitudegenerale',
            name='nom_prenom_medecin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificatbonnesante',
            name='nom_prenom_medecin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificatexemption',
            name='nom_prenom_medecin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='nom_prenom_medecin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificatprenuptial',
            name='nom_prenom_medecin',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
