# Generated by Django 5.2.11 on 2026-04-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_certificataptitudegenerale_nom_prenom_medecin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatbonnesante',
            name='destinataire',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificatexemption',
            name='motif_medical',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='classe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='duree_validite',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 an'), (2, '2 ans'), (5, '5 ans')], help_text='Durée de validité en années.', null=True),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='paragraphe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='sous_paragraphe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificatprenuptial',
            name='adresse_medecin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certificatprenuptial',
            name='attire_attention_rubeole',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificatprenuptial',
            name='insiste_facteurs_risque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificatprenuptial',
            name='numero_ordre_medecin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificatprenuptial',
            name='specialite_medecin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='certificatbonnesante',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificats_bonne_sante', to='consultations.consultation'),
        ),
    ]
