# Generated by Django 5.2.11 on 2026-04-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_certificatbonnesante_destinataire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatpermisconduire',
            name='cin_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificatpermisconduire',
            name='cin_delivree_a',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
