# Generated by Django 5.2.11 on 2026-04-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_alter_certificatpermisconduire_cin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatexemption',
            name='type_exemption',
        ),
        migrations.AddField(
            model_name='certificatexemption',
            name='motif_exemption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='lieu_exercice_medecin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='numero_ordre_medecin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificatprenuptial',
            name='adresse_patient',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certificatprenuptial',
            name='lieu_exercice_medecin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificatprenuptial',
            name='lieu_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='certificataptitudegenerale',
            name='apte_collectivite',
            field=models.BooleanField(default=False, verbose_name='Apte à être en collectivité'),
        ),
        migrations.AlterField(
            model_name='certificataptitudegenerale',
            name='apte_sport',
            field=models.BooleanField(default=False, verbose_name='Apte Pour Pratiquer Le Sport'),
        ),
        migrations.AlterField(
            model_name='certificataptitudegenerale',
            name='est_bonne_sante',
            field=models.BooleanField(default=False, verbose_name='En bonne santé clinique'),
        ),
        migrations.AlterField(
            model_name='certificataptitudegenerale',
            name='indemne_pathologie_contagieuse',
            field=models.BooleanField(default=False, verbose_name='Qu’il Est Indemne De Toute Pathologie Contagieuse'),
        ),
    ]
