# Generated by Django 5.2.11 on 2026-04-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0011_remove_certificatexemption_type_exemption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatpermisconduire',
            name='cin_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
