# Generated by Django 5.2.11 on 2026-04-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0012_alter_certificatpermisconduire_cin_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatbonnesante',
            name='apte_collectivite',
        ),
        migrations.RemoveField(
            model_name='certificatbonnesante',
            name='correctement_vaccine',
        ),
        migrations.RemoveField(
            model_name='certificatbonnesante',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='certificatbonnesante',
            name='indemne_maladies_contagieuses',
        ),
        migrations.RemoveField(
            model_name='certificatexemption',
            name='motif_exemption',
        ),
        migrations.RemoveField(
            model_name='certificatexemption',
            name='motif_medical',
        ),
    ]
