# Generated by Django 5.2.11 on 2026-04-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0013_remove_certificatbonnesante_apte_collectivite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='adresse_medecin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='gouvernorat_medecin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='ville_medecin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certificatprenuptial',
            name='gouvernorat_medecin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certificatprenuptial',
            name='ville_medecin',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
