# Generated by Django 5.2.11 on 2026-04-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0014_certificatpermisconduire_adresse_medecin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatprenuptial',
            name='attire_attention_rubeole',
        ),
        migrations.RemoveField(
            model_name='certificatprenuptial',
            name='conseil_genetique',
        ),
        migrations.RemoveField(
            model_name='certificatprenuptial',
            name='conseille_hepatite_b',
        ),
        migrations.RemoveField(
            model_name='certificatprenuptial',
            name='informe_resultats',
        ),
        migrations.RemoveField(
            model_name='certificatprenuptial',
            name='insiste_facteurs_risque',
        ),
        migrations.RemoveField(
            model_name='certificatprenuptial',
            name='planification_naissance',
        ),
    ]
