# Generated by Django 5.2.11 on 2026-04-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0015_remove_certificatprenuptial_attire_attention_rubeole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='adresse_residence',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
