# Generated by Django 5.2.11 on 2026-04-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0016_certificatpermisconduire_adresse_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatprenuptial',
            name='cin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificatprenuptial',
            name='cin_delivree_a',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
