# Generated by Django 5.2.11 on 2026-04-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0017_certificatprenuptial_cin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='lieu_exercice_medecin',
            field=models.CharField(blank=True, max_length=200, verbose_name='exerçant à'),
        ),
    ]
