# Generated by Django 5.2.11 on 2026-04-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0018_alter_certificatprenuptial_lieu_exercice_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='ville_medecin',
            field=models.CharField(blank=True, max_length=150, verbose_name='rue'),
        ),
    ]
