# Generated by Django 5.2.11 on 2026-04-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0019_alter_certificatprenuptial_ville_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='groupe_sanguin_fait',
            field=models.BooleanField(default=False, verbose_name='Groupe sanguin'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='hepatite_b_fait',
            field=models.BooleanField(default=False, verbose_name='Hepatite Virale B'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='hepatite_c_fait',
            field=models.BooleanField(default=False, verbose_name='Hepatite Virale C'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='radio_thorax_fait',
            field=models.BooleanField(default=False, verbose_name='Radiographie du Thorax par Rayon X'),
        ),
    ]
