# Generated by Django 5.2.11 on 2026-04-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0020_alter_certificatprenuptial_groupe_sanguin_fait_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatpermisconduire',
            name='adresse_medecin',
        ),
        migrations.RemoveField(
            model_name='certificatpermisconduire',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='certificatpermisconduire',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='certificatpermisconduire',
            name='duree_validite',
        ),
        migrations.RemoveField(
            model_name='certificatpermisconduire',
            name='gouvernorat_medecin',
        ),
        migrations.RemoveField(
            model_name='certificatpermisconduire',
            name='specialite_renvoi',
        ),
        migrations.RemoveField(
            model_name='certificatpermisconduire',
            name='ville_medecin',
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='certificat_delivre_par_specialiste',
            field=models.BooleanField(default=False, verbose_name='certificat délivré par un spécialiste en'),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='certificat_delivre_par_specialiste_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Type de spécialiste (certificat)'),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='examine_par_specialiste',
            field=models.BooleanField(default=False, verbose_name='examiné par un spécialiste en'),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='examine_par_specialiste_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Type de spécialiste (examen)'),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='inapte_conduite',
            field=models.BooleanField(default=False, verbose_name='est inapte à la conduite des véhicules'),
        ),
        migrations.AddField(
            model_name='certificatpermisconduire',
            name='inapte_conduite_raison',
            field=models.CharField(blank=True, max_length=255, verbose_name="Raison de l'inaptitude"),
        ),
        migrations.AlterField(
            model_name='certificatpermisconduire',
            name='lieu_exercice_medecin',
            field=models.CharField(blank=True, max_length=200, verbose_name='exerçant à'),
        ),
    ]
