# Generated by Django 5.2.11 on 2026-04-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0021_remove_certificatpermisconduire_adresse_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='adresse_medecin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse medecin'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='adresse_patient',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse patient'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='autres_examens',
            field=models.TextField(blank=True, verbose_name='Autres examens'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='cin',
            field=models.CharField(max_length=50, verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='cin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date delivrance CIN'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='cin_delivree_a',
            field=models.CharField(blank=True, max_length=200, verbose_name='CIN delivree a'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats_prenuptiaux', to='consultations.consultation', verbose_name='Consultation'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='date_emission',
            field=models.DateField(auto_now_add=True, verbose_name='Date emission'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='date_naissance',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='gouvernorat_medecin',
            field=models.CharField(blank=True, max_length=150, verbose_name='Gouvernorat medecin'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='lieu_naissance',
            field=models.CharField(max_length=200, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='lieu_signature',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu signature'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='nom_prenom',
            field=models.CharField(max_length=200, verbose_name='Nom et prenom'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='nom_prenom_medecin',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom et prenom medecin'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='numero_ordre_medecin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numero ordre medecin'),
        ),
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='specialite_medecin',
            field=models.CharField(blank=True, max_length=150, verbose_name='Specialite medecin'),
        ),
    ]
