# Generated by Django 5.2.11 on 2026-04-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0022_alter_certificatprenuptial_adresse_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatprenuptial',
            name='adresse_medecin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Numero Adresse medecin'),
        ),
    ]
