# Generated by Django 5.2.11 on 2026-04-09 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_site_medecin_site'),
        ('consultations', '0023_alter_certificatprenuptial_adresse_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='account.site'),
        ),
    ]
