# Generated by Django 5.2.11 on 2026-04-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_auto_link_medicaments'),
        ('consultations', '0024_consultation_site'),
    ]

    operations = [
    ]
