# Generated by Django 5.2.11 on 2026-03-07 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entree'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('acte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='stock.acteinfirmier')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stock.stockmedicament')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
