# Generated by Django 5.2.11 on 2026-03-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_mouvementstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='unite',
            field=models.CharField(choices=[('boite', 'Boite'), ('flacon', 'Flacon'), ('tube', 'Tube'), ('ampoule', 'Ampoule'), ('comprime', 'Comprime'), ('millilitre', 'Millilitre')], default='boite', max_length=20),
        ),
    ]
