# Generated by Django 5.2.11 on 2026-03-07 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_collaborateur_numero_cnss'),
        ('stock', '0003_medicament_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='acteinfirmier',
            name='type_acte',
            field=models.CharField(choices=[('DON', 'Don à un employé'), ('OUVERTURE', 'Ouverture de boîte')], default='OUVERTURE', max_length=20),
        ),
        migrations.AlterField(
            model_name='acteinfirmier',
            name='collaborateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actes_infirmiers', to='employees.collaborateur'),
        ),
    ]
