# Generated by Django 5.2.11 on 2026-03-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_acteinfirmier_type_acte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='conditionnement',
            field=models.CharField(choices=[('boite', 'Boîte'), ('flacon', 'Flacon'), ('tube', 'Tube'), ('sachet', 'Sachet'), ('plaquette', 'Plaquette'), ('unite', 'Unité')], default='boite', help_text='Emballage dans lequel le médicament est reçu (boîte, flacon…)', max_length=20, verbose_name='Conditionnement'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='qte_par_conditionnement',
            field=models.PositiveIntegerField(default=1, help_text="Nombre d'unités de dispensation par conditionnement. Ex: 30 comprimés/boîte", verbose_name='Qté par conditionnement'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='unite',
            field=models.CharField(choices=[('comprime', 'Comprimé'), ('ampoule', 'Ampoule'), ('millilitre', 'Millilitre'), ('sachet', 'Sachet'), ('gelule', 'Gélule'), ('suppositoire', 'Suppositoire'), ('patch', 'Patch'), ('unite', 'Unité')], default='comprime', help_text='Unité dans laquelle on donne au patient (comprimé, ampoule…)', max_length=20, verbose_name='Unité de dispensation'),
        ),
    ]
