# Generated by Django 5.2.11 on 2026-03-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_medicament_conditionnement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='conditionnement_personnalise',
            field=models.CharField(blank=True, default='', help_text="Rempli uniquement si conditionnement='autre'", max_length=60, verbose_name='Conditionnement personnalisé'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='conditionnement',
            field=models.CharField(choices=[('boite', 'Boîte'), ('flacon', 'Flacon'), ('tube', 'Tube'), ('sachet', 'Sachet'), ('plaquette', 'Plaquette'), ('unite', 'Unité'), ('autre', 'Autre')], default='boite', help_text='Emballage dans lequel le médicament est reçu (boîte, flacon…)', max_length=20, verbose_name='Conditionnement'),
        ),
    ]
