# Generated by Django 5.2.11 on 2026-03-19 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_collaborateur_plant_section_collaborateur_segment'),
        ('stock', '0006_medicament_conditionnement_personnalise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='collaborateur',
            field=models.ForeignKey(blank=True, help_text='Rempli si la sortie est nominative (dispensation à un collaborateur)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='employees.collaborateur', verbose_name='Collaborateur bénéficiaire'),
        ),
    ]
