# Generated by Django 5.2.11 on 2026-03-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_mouvementstock_collaborateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='conditionnement',
            field=models.CharField(choices=[('boite', 'Boite'), ('flacon', 'Flacon'), ('tube', 'Tube'), ('sachet', 'Sachet'), ('plaquette', 'Plaquette'), ('unite', 'Unite'), ('autre', 'Autre')], default='boite', help_text='Emballage dans lequel le medicament est recu (boite, flacon...)', max_length=20, verbose_name='Conditionnement'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='conditionnement_personnalise',
            field=models.CharField(blank=True, default='', help_text="Rempli uniquement si conditionnement='autre'", max_length=60, verbose_name='Conditionnement personnalise'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='qte_par_conditionnement',
            field=models.PositiveIntegerField(default=1, help_text="Nombre d'unites de dispensation par conditionnement. Ex: 30 comprimes/boite", verbose_name='Qte par conditionnement'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='unite',
            field=models.CharField(choices=[('comprime', 'Comprime'), ('ampoule', 'Ampoule'), ('millilitre', 'Millilitre'), ('sachet', 'Sachet'), ('gelule', 'Gelule'), ('suppositoire', 'Suppositoire'), ('patch', 'Patch'), ('unite', 'Unite')], default='comprime', help_text='Unite dans laquelle on donne au patient (comprime, ampoule...)', max_length=20, verbose_name='Unite de dispensation'),
        ),
    ]
